general:
  debug: false
  instance_name: "Powerful Search"
  limit: 10
  contact_url: "https://visitpowerful.com"
  enable_metrics: true
  outgoing_requests:
    proxies: {}
    user_agent_suffix: "PowerfulBot"

search:
  safe_search: 1  # 0: off, 1: moderate, 2: strict
  language: "en"
  autocomplete: "duckduckgo"
  default_engine: "google"
  disabled_engines: []
  result_count: 10

ui:
  theme: "simple"
  default_locale: "en"
  show_image_preview: true
  infinite_scroll: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "powerfulpankajhere310"
  base_url: "https://chat.visitpowerful.com"
  image_proxy: true

engines:
  - name: google
    engine: google
    disabled: false

  - name: bing
    engine: bing
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    disabled: false

  - name: wikipedia
    engine: wikipedia
    disabled: false

# Remove this block if Redis is not configured
redis:
  url: redis://default:@localhost:6379
